# Generated by Django 5.2.2 on 2025-06-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usd',
            options={'ordering': ('-time',)},
        ),
    ]
