# Generated by Django 5.2.2 on 2025-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usd', '0002_alter_usd_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usd',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
