# Generated by Django 5.2.2 on 2025-06-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usd', '0004_currency_currencyrate_delete_usd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together=set(),
        ),
    ]
